### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by jazbogross** [StaticJsCMS/static-cms#1085]
When I create a new post I get an error in the preview window with the following console output:

cms.be93d.js:120 RangeError: Invalid time value
    at ne (cms.be93d.js:120:2229572)
    at pe (cms.be93d.js:120:2233729)
    at xa (cms.be93d.js:120:2121097)
    at xl (cms.be93d.js:120:2177952)
    at bc (cms.be93d.js:120:2167104)
    at vc (cms.be93d.js:120:2167032)
    at Oc (cms.be93d.js:120:2166895)
    at ac (cms.be93d.js:120:2163702)
    at oc (cms.be93d.js:120:2162254)
    at k (cms.be93d.js:120:2195364)

Once I enter info into the frontmatter fields and save I get a working preview. There is no problem when editing existing posts. The error only happens at the first instance of creating a new post. I know that open authoring is in Beta, but this was happening before I changed to editorial workflow.

**To Reproduce**
I created this from the Hugo template. I have made content and layout changes but everything else remains the same and the problem was there before the changes I made so I would think the issue is there from the beginning when spinning up a site from the Hugo template.

**Expected behavior**
Preview of the changes made in frontmatter on a new post. No error message.

**Screenshots**
<img width="1548" alt="Screenshot 2024-02-16 at 13 20 22" src="https://github.com/StaticJsCMS/static-cms/assets/57679104/ac2199ac-c290-415e-85a3-0eaa78d7309e">

**Applicable Versions:**
 - Static CMS version: `@staticcms/core@4.0.0`
 - Git provider: `github`
 - Browser version: `Brave v 1.62.162 `

**CMS configuration**
```
backend:
  name: github
  repo: saragebran/oikos-archive
  open_authoring: true
publish_mode: editorial_workflow
media_folder: site/static/img
public_folder: /img
local_backend: true
collections:
 [... everything after this point is identical to the template...]

**Comment by KaneFreeman** [comment]
Please try updating to the most recent version `v4.3.0` and let me know if you are still experiencing this issue. The datepicker library was updates significantly since `v4.0.0`.
